### ISSUE TITLE
LICENSE.md missing

### ISSUE THREAD

**Issue by dotqaghan** [rafi4204/android-compose-template#1]
From [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository):
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

The README mentions a LICENSE.md file, but I could not find such file. Please add it if it is missing.

**Comment by rafi4204** [comment]
License has been added
